### ISSUE TITLE
Error after instalation

### ISSUE THREAD

**Issue by viniciusm-dev** [JBakamovic/cxxd-vim#3]
Hi, after I install the cxxd following the steps, that error occurs when vim starts.

```
Erro detectado ao processar /home/jonrock/.vim/bundle/cxxd-vim/plugin/cxxd/server.vim:
linha   10:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jonrock/.vim/bundle/cxxd-vim/lib/cxxd/api.py", line 1, in <module>
    from server import ServiceId
  File "/home/jonrock/.vim/bundle/cxxd-vim/lib/cxxd/server.py", line 8, in <module>
    from services.source_code_model_service import SourceCodeModel
  File "/home/jonrock/.vim/bundle/cxxd-vim/lib/cxxd/services/source_code_model_service.py", line 4, in <module>
    import cxxd.parser.clang_parser
  File "/home/jonrock/.vim/bundle/cxxd-vim/lib/cxxd/parser/clang_parser.py", line 1, in <module>
    import clang.cindex
ImportError: No module named clang.cindex
```

**Comment by JBakamovic** [comment]
You're missing the Python bindings for libclang.

**Comment by viniciusm-dev** [comment]
Evertything working now, thank you!
