### ISSUE TITLE
[xcb] Unknown sequence number while processing queue | How to install it correctly?

### ISSUE THREAD

**Issue by Mesysz** [JBakamovic/cxxd-vim#6]
Hello :) so..

Edit: Sorry for being impolite and only pointing an error ;c **Is there any way you could help me with that problem?**

At first, I tried to install cxxd-vim to my vim and after recompiling vim to have **+servername**, **+python** and so, I tried to start it.

`:CxxdStart .` gives me this error:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
gvim: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
And after wandering through the whole internet for 3 times at least, I have no idea why is it happening.

Another situation that occured is: when I use `:CxxdStart .` in vim (not Gvim), it starts 4 another Gvim windows with respectively:
`<ect_builder#start_callback(1) 0, 0-1`
`<#clang_tidy#start_callback(1) 0, 0-1`
`<lang_format#start_callback(1) 0, 0-1`
`<code_model#start_callback(1) 0, 0-1`
in the bottom bars.

I have **compile_flags.txt** with 
```
-I./
-Wall
-Werror
```
that, as you said, is required.

Also `:CxxdFetchAllDiagnostics` does nothing. Everything does nothing, lol.

I can run `:CxxdStart .` inside one of those windows and after that the window freezes and I get 
error in **python 2.7/multiprocessing/process.py** error, lines **267** and **114**, 
error in **cxxd-vim/lib/cxxd/service.py**, lines **62**, **41**, 
error in **cxxd-vim/lib/cxxd/services/source_code_model_service.py**, line **52**,
error in **cxxd-vim/lib/cxxd/services/source_code_model/indexer/clang_indexer.py**, line **72**.
Couldn't copy that, that windows is frozen and have to `kill -9` now :(

`vim --version`
```VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2020 17:29:27)
Included patches: 1-480
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
-arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary

```
Also, about the c++ code: it's a simple hello-world program where the print function is inside another class, with only `#include<iostream>` and `#include<header.h>`.  

And I'm using Arch Linux (btw, lol).

If I can provide any more help, just tell me what you want :)

**Edit2:** After recompiling vim using `--enable-gui=gtk3` instead of `--enable-gui=gtk2` I'm able to run `:CxxdStart .` in Gvim (started using `gvim --servername cxxd -f .`), but after that I get 
```
0
0
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
gvim: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Vim: Caught deadly signal ABRT
BadLength (poly request too large or internal Xlib length error)
Vim: Got X error
Vim: Finished.
```
aaaaaand it's frozen again.

Anyway, is cxxd-vim supposed to run only in Gvim? Or there is a way to make it run in vim inside terminal? I'm not used to Gvim and don't think I want to :D.

**Comment by JBakamovic** [comment]
Hi,

Can you please do the following:

1. Run `gvim` provided by your distro (and not the custom built one by you).
2. Execute `:CxxdStart <path_to_your_source_code>`.
3. Paste the contents of `/tmp/GVIM_server.log` file here.

**Comment by Mesysz** [comment]
**/tmp/GVIM_server.log**:
```
[20:45:25.434] [INFO] [api.py:37]                __run_impl(): Starting a server for /home/user/c++/c++project
[20:45:25.434] [INFO] [cxxd_config_parser.py:42]                  __init__(): Configuration: Type auto-discovery-try-harder
[20:45:25.434] [INFO] [cxxd_config_parser.py:43]                  __init__(): Configuration: Selected None
[20:45:25.434] [INFO] [cxxd_config_parser.py:44]                  __init__(): Indexer: Blacklisted directories []
[20:45:25.434] [INFO] [cxxd_config_parser.py:45]                  __init__(): Indexer: Extra file extensions []
[20:45:25.434] [INFO] [cxxd_config_parser.py:46]                  __init__(): Clang-tidy args []
[20:45:25.434] [INFO] [cxxd_config_parser.py:47]                  __init__(): Clang-tidy binary path /usr/bin/clang-tidy
[20:45:25.434] [INFO] [cxxd_config_parser.py:48]                  __init__(): Clang-format args []
[20:45:25.434] [INFO] [cxxd_config_parser.py:49]                  __init__(): Clang-format binary path /usr/bin/clang-format
[20:45:25.434] [INFO] [cxxd_config_parser.py:50]                  __init__(): Project-builder args []
[20:45:25.434] [INFO] [cxxd_config_parser.py:155] _extract_configuration_for_target(): Looking at /home/user/c++/c++project/. path
[20:45:25.434] [INFO] [cxxd_config_parser.py:161] _extract_configuration_for_target(): Auto-discovery-try-harder mode: found 'compile_commands.json' under /home/user/c++/c++project.
[20:45:25.435] [INFO] [service.py:16]                  __init__(): Actions: {0: <bound method SourceCodeModel.__startup_request of <cxxd.services.source_code_model_service.SourceCodeModel instance at 0x7fe22754df50>>, 1: <bound method SourceCodeModel.__shutdown_request of <cxxd.services.source_code_model_service.SourceCodeModel instance at 0x7fe22754df50>>, 2: <bound method SourceCodeModel.__request of <cxxd.services.source_code_model_service.SourceCodeModel instance at 0x7fe22754df50>>}
[20:45:25.435] [INFO] [cxxd_config_parser.py:155] _extract_configuration_for_target(): Looking at /home/user/c++/c++project. path
[20:45:25.435] [INFO] [cxxd_config_parser.py:161] _extract_configuration_for_target(): Auto-discovery-try-harder mode: found 'compile_commands.json' under /home/user/c++/c++project/.
[20:45:25.606] [INFO] [compiler_args.py:83]                  __init__(): Compiler args filename = /home/user/c++/c++project/./compile_commands.json. Default compiler args = ['-x', 'c++', '-I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu', '-I/usr/lib/clang/9.0.1/include', '-I/usr/include', '-I/usr/local/include', '-I/usr/include/c++/9.3.0/backward', '-I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include', '-I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed', '-I/usr/include/c++/9.3.0']
[20:45:25.606] [INFO] [clang_parser.py:65]                  __init__(): libclang version: 'clang version 9.0.1 '
[20:45:25.606] [INFO] [service.py:16]                  __init__(): Actions: {0: <bound method ProjectBuilder.__startup_request of <cxxd.services.project_builder_service.ProjectBuilder instance at 0x7fe2111a1f00>>, 1: <bound method ProjectBuilder.__shutdown_request of <cxxd.services.project_builder_service.ProjectBuilder instance at 0x7fe2111a1f00>>, 2: <bound method ProjectBuilder.__request of <cxxd.services.project_builder_service.ProjectBuilder instance at 0x7fe2111a1f00>>}
[20:45:25.607] [INFO] [project_builder_service.py:17]                  __init__(): Build command will be executed from '/home/user/c++/c++project/' directory. Output will be recorded into '/tmp/tmpAFB8ko_project_build_output'.
[20:45:25.607] [INFO] [service.py:16]                  __init__(): Actions: {0: <bound method ClangFormat.__startup_request of <cxxd.services.clang_format_service.ClangFormat instance at 0x7fe2111aa5a0>>, 1: <bound method ClangFormat.__shutdown_request of <cxxd.services.clang_format_service.ClangFormat instance at 0x7fe2111aa5a0>>, 2: <bound method ClangFormat.__request of <cxxd.services.clang_format_service.ClangFormat instance at 0x7fe2111aa5a0>>}
[20:45:25.607] [INFO] [service.py:16]                  __init__(): Actions: {0: <bound method ClangTidy.__startup_request of <cxxd.services.clang_tidy_service.ClangTidy instance at 0x7fe2111aad20>>, 1: <bound method ClangTidy.__shutdown_request of <cxxd.services.clang_tidy_service.ClangTidy instance at 0x7fe2111aad20>>, 2: <bound method ClangTidy.__request of <cxxd.services.clang_tidy_service.ClangTidy instance at 0x7fe2111aad20>>}
[20:45:25.607] [INFO] [cxxd_config_parser.py:155] _extract_configuration_for_target(): Looking at /home/user/c++/c++project/. path
[20:45:25.607] [INFO] [cxxd_config_parser.py:161] _extract_configuration_for_target(): Auto-discovery-try-harder mode: found 'compile_commands.json' under /home/user/c++/c++project/.
[20:45:25.607] [INFO] [clang_tidy_service.py:27]                  __init__(): clang-tidy will extract compiler flags from existing JSON database.
[20:45:25.646] [INFO] [clang_tidy_service.py:36]                  __init__(): clang-tidy version: 'LLVM (http://llvm.org/):
  LLVM version 9.0.1
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
[20:45:25.646] [INFO] [server.py:90]                  __init__(): Registered services: {0: <cxxd.server.ServiceHandler instance at 0x7fe2111a1eb0>, 1: <cxxd.server.ServiceHandler instance at 0x7fe2111aa5f0>, 2: <cxxd.server.ServiceHandler instance at 0x7fe2111aacd0>, 3: <cxxd.server.ServiceHandler instance at 0x7fe2111b2460>}
[20:45:25.646] [INFO] [server.py:91]                  __init__(): Actions: {240: <bound method Server.__start_all_services of <cxxd.server.Server instance at 0x7fe22754db40>>, 241: <bound method Server.__start_service of <cxxd.server.Server instance at 0x7fe22754db40>>, 242: <bound method Server.__send_service_request of <cxxd.server.Server instance at 0x7fe22754db40>>, 253: <bound method Server.__shutdown_all_services of <cxxd.server.Server instance at 0x7fe22754db40>>, 254: <bound method Server.__shutdown_service of <cxxd.server.Server instance at 0x7fe22754db40>>, 255: <bound method Server.__shutdown_and_exit of <cxxd.server.Server instance at 0x7fe22754db40>>}
[20:45:25.646] [INFO] [server.py:111]           __start_service(): id=0, service='SourceCodeModel', payload=[]
[20:45:25.647] [INFO] [server.py:111]           __start_service(): id=3, service='ClangTidy', payload=[]
[20:45:25.648] [INFO] [service.py:22]         __startup_request(): Service startup ... Payload = []
[20:45:25.649] [INFO] [server.py:111]           __start_service(): id=2, service='ClangFormat', payload=[]
[20:45:25.649] [INFO] [service.py:22]         __startup_request(): Service startup ... Payload = []
[20:45:25.650] [INFO] [server.py:111]           __start_service(): id=1, service='ProjectBuilder', payload=[]
[20:45:25.651] [INFO] [service.py:22]         __startup_request(): Service startup ... Payload = []
[20:45:25.652] [INFO] [service.py:22]         __startup_request(): Service startup ... Payload = []
[20:45:25.664] [INFO] [server.py:152]    __send_service_request(): id=0, service='SourceCodeModel', Payload=[0, 1]
[20:45:25.665] [INFO] [service.py:40]                 __request(): Service request ... Payload = [0, 1]
[20:45:25.674] [INFO] [clang_format_service.py:30]          startup_callback(): clang-format version: 'clang-format version 9.0.1'
[20:45:25.693] [CRITICAL] [api.py:16]        __handle_exception(): Uncaught exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/plugged/cxxd-vim/lib/cxxd/api.py", line 67, in server_stop
    handle.put([ServerRequestId.SHUTDOWN_AND_EXIT, 0x0, list(payload)])
AttributeError: 'NoneType' object has no attribute 'put'
```
(Changed $PATH to remove names but it was a valid path to a c++ project)
Can I make it look like a spoiler, so it's hidden from the start?
Btw, I got the same error in console:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
gvim: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Vim: Caught deadly signal ABRT
Vim: Finished.
```
after **:CxxdStart .**
and gvim freezes, too.

Can it be used only in gvim? Or can I use it in terminal vim, too?
Also, I'm curious - why the one built by me is "bad"? Are there some options that I included that were unnecessary? Or you want to exclude the possibility that I might do sth wrong? I'm asking because I want to know stuff instead of just fixing it not knowing what have happened :D
